/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package com.smarthire.xander.interfaces;

/**
 *
 * @author Zander Lumapac
 */
public interface LatinAndGreekAffixes {
    public final String[][] latinPrefix = {
        {"A", "-1"},
        {"AB,ABS", "-1"},
        {"AD,AC,AN,AS", "1"},
        {"AMBI,AMB", "-1"},
        {"ANTE", "1"},
        {"ARCH", "1"},
        {"BI", "1"},
        {"BENE", "1"},
        {"CIRCUM,CIRA", "1"},
        {"CIS", "1"},
        {"CON", "-1"},
        {"COM,COR,COL", "1"},
        {"CONTRA", "-1"},
        {"COUNTER", "-1"},
        {"DE", "-1"},
        {"DEMI","1"},
        {"DIS, DI, DIF","-1"},
        {"DU, DUO","1"},
        {"EM, EN", "1"},
        {"EX, E, EF, EC", "-1"},
        {"EXTRA,EXTRO","1"},
        {"FORE", "-1"},
        {"IN, I, IL, IM, IR","-1"},
        {"INDU, INDI", "-1"},
        {"INFRA" , "-1"},
        {"INTER, INTEL", "1"},
        {"INTRA","1"},
        {"INTRO","1"},
        {"JUXTA", "1"},
        {"MAL, MALE" , "-1"},
        {"MEDI, MEDIO" , "-1"},
        {"MILLI, MILLE" , "1"},
        {"MONO", "1"},
        {"MULTI, MULTUS","1"},
        {"NE" , "-1"},
        {"NON", "-1"},
        {"NUL, NULL" , "-1"},
        {"OB, OF, OC", "-1"},
        {"OP, O", "-1"},
        {"OMNI", "1"},
        {"PED, PEDI", "1"},
        {"PER, PEL" , "1"},
        {"POST", "1"},
        {"PRE", "1"},
        {"PRO, PUR" ,"1"},
        {"QUADRI, QUADR" , "1"},
        {"RE, RED" , "-1"},
        {"RETRO" , "1"},
        {"SE, SED", "1"},
        {"SEMI", "1"},
        {"SINE", "-1"},
        {"SUB, SUC, SUF", "-1"},
        {"SUG, SUM, SUP", "1"},
        {"SUR, SUS", "-1"},
        {"SUBTER" , "-1"},
        {"SUPER, SUPRA" , "1"},
        {"SUR" , "-1"},
        {"TRANS, TRA" , "1"},
        {"TRI" , "1"},
        {"ULTRA" , "1"},
        {"UN", "-1"}
    };
    
    public final String[][] latinSuffix = {
        {"ABLE, ABLY", "1"},
        {"ACY","1"},
        {"AGE", "1"},
        {"AL", "1"},
        {"ANA", "1"},
        {"AN, ANT, ENT" , "1"},
        {"ANCE","-1"},
        {"ARY" , "1"},
        {"ATE" , "1"},
        {"ATION, ITION " , "1"},
        {"AR" , "1"},
        {"BULUM,BLE" , "1"},
        {"CIDE, CIDAL", "-1"},
        {"CRAT,CRACY" , "1"},
        {"CULUM, CLE" , "1"},
        {"EN", "-1"},
        {"ENCE", "1"},
        {"ENCY", "1"},
        {"ER,OR" , "1"},
        {"ENT" , "1"},
        {"ERY, RY", "1"},
        {"ESCE", "1"},
        {"FY" , "1"},
        {"HOOD" , "1"},
        {"IAN", "1"},
        {"IER" , "1"},
        {"IBLE" , "1"},
        {"IC" , "1"},
        {"ICE" , "1"},
        {"IL, ILE", "1"},
        {"ION", "1"},
        {"IUM, Y, CE, GE", "1"},
        {"CIUM, TIUM, GIUM" , "1"},
        {"ISH" , "1"},
        {"IST","1"},
        {"ITIOUS", "1"},
        {"ITUDE,TUDE" , "1"},
        {"ITY" , "1"},
        {"IVE", "1"},
        {"LESS","-1"},
        {"LIKE" , "1"},
        {"LY", "1"},
        {"MEN" , "1"},
        {"MENTUM, MENT", "1"},
        {"NESS" , "1"},
        {"OON", "1"},
        {"OR", "1"},
        {"ORY", "1"},
        {"OSE, OUS" , "-1"},
        {"SHIP" , "1"},
        {"SOME", "1"},
        {"TION" , "1"},
        {"TUDE" , "1"},
        {"ULUS, ULOUS" , "1"},
        {"URE", "1"},
        {"UUS, UOUS","1"},
        {"VOROUS, VORE" , "1"},
        {"WISE" , "1"},
        {"Y" , "1"}
    };
    
    public final String[][] greekPrefix = {
        {"A, AN", "-1"},
        {"ACRO" , "1"},
        {"ALLO" , "1"},
        {"AMB, AMPHI", "1"},
        {"AMB, AMPH" , "1"},
        {"ANA, AN" ,"1"},
        {"ANDRO, ANDR", "1"},
        {"ANTI, ANT" , "-1"},
        {"APO, AP" , "1"},
        {"ARCHAE" , "1"},
        {"AUTO" , "1"},
        {"BI" , "1"},
        {"CACO" , "-1"},
        {"CATA, CAT", "-1"},
        {"DECA" , "1"}, 
        {"DERMAT" , "1"},
        {"DEUTERO" , "1"}, 
        {"DIA, DI" , "1"},
        {"DIS, DI" , "1"},
        {"DYS" , "-1"},
        {"EC, EX" , "1"},
        {"ECO" , "1"},
        {"ECTO" , "1"},
        {"EN, EM" , "1"},
        {"ENDO" , "1"},
        {"ENNEA" , "1"},
        {"EPI, EP" , "1"},
        {"ESO" , "1"},
        {"EU" , "1"},
        {"EXO" , "1"},
        {"HECATO" , "1"},
        {"HEMI" , "1"},
        {"HEPTA" , "1"},
        {"HETERO" , "1"},
        {"HEXA" , "1"},
        {"HIER" , "1"},
        {"HOLO" , "1"},
        {"HOMEO", "1"},
        {"HOMO" , "1"},
        {"HYPER" , "1"},
        {"HYPO" , "-1"},
        {"IDIO" , "1"},
        {"IDEO" , "1"},
        {"ISO" , "1"},
        {"KILO" , "1"},
        {"MACRO" , "1"},
        {"MEGA, MEGALO" , "1"},
        {"MESO" , "1"},
        {"META" , "1"},
        {"MICRO" , "1"},
        {"MONO" , "1"},
        {"MYRIAD" , "1"},
        {"NEO" , "1"},
        {"OCTO" , "1"},
        {"OLIG" , "1"},
        {"ORTHO" , "1"},
        {"PALEO" , "1"},
        {"PALIN, PALI" , "1"},
        {"PAN" , "1"},
        {"PARA" , "1"},
        {"PACHY" , "1"}, 
        {"PENTA", "1"},
        {"PERI" , "1"},
        {"POLY" , "1"},
        {"PRO" , "1"},
        {"PROS" , "1"},
        {"PROTO" , "1"},
        {"PSEUDO" , "-1"},
        {"SCHIZO" , "-1"},
        {"SYN, SYM, SYS" , "1"},
        {"TAUTO" , "1"},
        {"TELE" , "1"},
        {"TELEO" , "1"},
        {"TETRA" , "1"},
        {"TRI", "1"}
    };
    
    public final String[][] greekSuffix = {
        {"AC,IAC" , "1"},
        {"AGIA, ALGIA" , "-1"},
        {"AST" , "1"},
        {"CRACY" , "1"},
        {"CLASM" , "-1"},
        {"EMIA" , "-1"},
        {"GENESIS" , "1"},
        {"GENIC", "1"},
        {"GRAM" , "1"},
        {"GRAPH" , "1"}, 
        {"GRAPHY" , "1"},
        {"IA, Y" , "1"},
        {"IATRICS" , "1"},
        {"IATRY" , "1"},
        {"IC" , "1"},
        {"ICAL" , "1"},
        {"IC, ICE" , "1"},
        {"INE", "1"},
        {"ITE" ,"1"},
        {"ITIS", "-1"},
        {"ISE, IZE" , "1"},
        {"ISK, ISCUS" , "1"},
        {"ISM" , "1"},
        {"IST" , "1"},
        {"LATRY" , "1"},
        {"LITE, LITH" , "1"},
        {"LOGUE" , "1"},
        {"LOGY" , "1"},
        {"LYSIS" , "1"},
        {"MA, M, ME" , "1"},
        {"MANCY" , "1"},
        {"MANIA" , "-1"},
        {"METER" , "1"},
        {"OID" , "1"},
        {"OLOGY" , "1"},
        {"OMA" , "-1"},
        {"ORAMA" , "1"},
        {"OSIS" , "-1"},
        {"PATHY" , "-1"},
        {"PHILIA" , "1"},
        {"PHILIC" , "1"},
        {"PHOBIA" , "-1"},
        {"PHOR", "1"},
        {"PHORIA" , "1"},
        {"PHOROUS", "1"},
        {"POLY" , "1"},
        {"SCOPE" , "1"},
        {"SIS" , "1"},
        {"THERAPY" , "1"},
        {"TIC" , "1"},
        {"Y", "1"}
    };
    
            
            
             
    
}
